config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get :home, to: "pages#home"
  root to: "organisations#index"
  resources :organisations do
    resources :organisation_users do
      resources :shifts
    end
  end
  resources :organisation_users do
    member do
      post :join
      delete :leave
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :organisation_users, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :hourly_rate, presence: true
end

app/models/organisation_user.rb
class OrganisationUser < ApplicationRecord
  belongs_to :user
  belongs_to :organisation
  has_many :shifts, dependent: :destroy
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :organisation_user

  def shift_date
    # just prefer this style more
    start.to_s.split[0] if start
  end

  def start_time
    return unless start

    start.strftime("%H:%M")
  end

  def finish_time
    return unless finish

    finish.strftime("%H:%M")
  end

  def overnight
    finish.strftime("%D") > start.strftime("%D")
  end

  def break_hours
    break_length.fdiv(60).round(2)
  end

  def hours_worked
    (TimeDifference.between(start, finish).in_seconds / 3600).round(2)
  end

  def break_pay(length, rate)
    length * rate
  end

  def sunday_shift
    start.sunday? || finish.sunday?
  end

  def normal_pay
    (organisation_user.organisation.hourly_rate * hours_worked).round(2)
  end

  def penalty_pay
    rate = organisation_user.organisation.hourly_rate

    if start.sunday? && finish.sunday?
      normal_pay * 2 - break_pay(break_hours, rate * 2)
    elsif start.sunday? && finish.monday?
      sunday_pay = TimeDifference.between(start, start.end_of_day).in_minutes.fdiv(60) * rate
      net_pay = normal_pay + sunday_pay
      # Subtract break money
      monday_length = TimeDifference.between(finish.beginning_of_day, finish).in_minutes.fdiv(60)
      if monday_length >= break_hours
        break_pay = break_pay(break_hours, rate)
      else
        sunday_break_hours = break_hours - monday_length
        break_pay = break_pay(monday_length, rate) + break_pay(sunday_break_hours, rate * 2)
      end
      (net_pay - break_pay).round(2)

    elsif start.saturday? && finish.sunday?
      sunday_length = TimeDifference.between(finish.beginning_of_day, finish).in_minutes.fdiv(60)
      net_pay = sunday_length * rate + normal_pay
      if sunday_length >= break_hours
        break_pay = break_pay(break_hours, rate * 2)
      else
        saturday_break_hours = break_hours - sunday_length
        break_pay = break_pay(sunday_length, rate * 2) + break_pay(saturday_break_hours, rate)
      end
      (net_pay - break_pay).round(2)
    end
  end

  def final_pay
    if !sunday_shift
      normal_pay
    else
      penalty_pay
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :organisation_users, dependent: :destroy

  # validates :name, uniqueness: true, presence: true
  # validates :email, format: { with: /\A.*@.*\.com\z/ }, uniqueness: true, presence: true
  # validates :password, length: { minimum: 6 }, presence: true

  # validates

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password])
  end
end

app/controllers/organisation_users_controller.rb
class OrganisationUsersController < ApplicationController
  def join
    OrganisationUser.create(
      user_id: current_user.id,
      organisation_id: params[:id]
    )
    redirect_to organisations_path, status: :see_other
  end

  def leave
    organisation = Organisation.find(params[:id])
    my_org_user = OrganisationUser.where('user_id = ? AND organisation_id = ?', current_user.id, organisation.id)
    my_org_user[0].destroy
    redirect_to organisations_path, status: :see_other
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[show update destroy]

  def index
    if user_signed_in?
      organisations = Organisation.all

      my_org_users = OrganisationUser.where('user_id = ?', current_user.id)
      @my_orgs = my_org_users.map(&:organisation)

      @not_my_orgs = organisations.reject do |o|
        @my_orgs.include? o
      end
      # raise
      @organisation = Organisation.new
    else
      redirect_to home_path
    end
  end

  def show
    if user_signed_in?
      @all_org_users = OrganisationUser.where('organisation_id = ?', params[:id])
      @shifts = @all_org_users.map(&:shifts).flatten
      @shift = Shift.new
      @me = @all_org_users.find { |organisation_user| organisation_user.user == current_user }
    else
      redirect_to home_path
    end
  end

  def new
    @organisation = Organisation.new
  end

  def create
    organisation = Organisation.new(organisation_params)
    if organisation.save
      OrganisationUser.create(
        user_id: current_user.id,
        organisation_id: organisation.id
      )
      redirect_to join_organisation_user_path(organisation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @organisation.update(organisation_params)
    redirect_to organisation_path(organisation_params)
  end

  def destroy
    @organisation.destroy
    redirect_to organisations_path, status: :see_other
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name, :hourly_rate)
  end

  def set_organisation
    @organisation = Organisation.find(params[:id])
  end
end
  # def check_log_in
  #   return if user_signed_in?

  #   redirect_to home_path
  # end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    redirect_to organisations_path if user_signed_in?
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :find_organisation, only: %i[update destroy]

  def new
    @shift = Shift.new
  end

  def create
    year = params["shift"]["shift_date(1i)"].to_i
    month = params["shift"]["shift_date(2i)"].to_i
    day = params["shift"]["shift_date(3i)"].to_i
    start_h = params["shift"]["start_time(4i)"].to_i
    start_m = params["shift"]["start_time(5i)"].to_i
    finish_h = params["shift"]["finish_time(4i)"].to_i
    finish_m = params["shift"]["finish_time(5i)"].to_i
    break_length = params["shift"]["break_length"].to_i
    organisation_user_id = params["organisation_user_id"].to_i
    organisation = Organisation.find(params["organisation_id"].to_i)

    start = DateTime.new(year, month, day, start_h, start_m, 0)
    finish = DateTime.new(year, month, day, finish_h, finish_m, 0)

    if finish_h < start_h
      finish = finish.next_day(1)
    end

    shift = Shift.new(
      start: start,
      finish: finish,
      break_length: break_length,
      organisation_user_id: organisation_user_id
    )

    shift.save unless start == finish || start <= Time.now
    redirect_to organisation_path(organisation)
  end

  def update
    shift.update(shift_params)
    redirect_to organisation_path(@organisation)
  end

  private

  def shift_params
    params.require(:shift).permit(:start, :finish, :break_length)
  end

  def find_organisation
    @organisation = Organisation.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    user.update(user_params)
    redirect_to organisations_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisation_users_helper.rb
module OrganisationUsersHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/organisations/index.html.erb
<div class="p-3 mt-2">
  <h2>My Organisations</h2>

  <% if @my_orgs.length>0 %>
    <ul>
      <% @my_orgs.each do |o| %>
        <li>
          <%= o.name %>
          <div >
            <button class="btn btn-secondary"><%=link_to "View ", organisation_path(o) %></button>

            <button class="btn btn-dark"><%=link_to "Leave", leave_organisation_user_path(o), data: {turbo_method: :delete} %></button>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>You're not in any organisations</p>
  <% end %>
</div>

<div class="p-3"data-controller="organisation">

  <div data-action="click->organisation#toggleForm" class="btn btn-primary">Create an organisation</div>
  <div >
    <%= simple_form_for @organisation, html:{data: {organisation_target: "form"}, class: "invisible" } do |f| %>
      <%= f.input :name, placeholder:'Minimum 5 letters'%>
      <%= f.input :hourly_rate, placeholder:'£' %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

<div class="p-3">
  <h2>Other Organisations</h2>

  <% if @not_my_orgs.length>0 %>
    <ul>
      <% @not_my_orgs.each do |o| %>
        <li>
        <div class="mt-1">
          <%= o.name %>
            <button class="btn btn-dark">
              <%= link_to "Join", join_organisation_user_path(o), data: {turbo_method: :post}  %>
            </button>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Working hard! You're in every org!</p>
  <% end %>

</div>

app/views/organisations/show.html.erb
<% if user_signed_in? %>
<div class="m-3">
  <%= link_to "back to all organisations", organisations_path%>
</div>

<div class="m-3">
  <h1>
    <%= @organisation.name %>
  </h1>
  <h2>
    Hourly Rate: £ <%= @organisation.hourly_rate %>
  </h2>
    <div class="d-flex" >
      <div class="me-2" data-controller="organisation">
        <button data-action="click->organisation#toggleForm" type="button" class="btn btn-dark">Edit</button>
          <%= simple_form_for @organisation, html: { data: { organisation_target: "form" }, class: "invisible" } do |f| %>
            <%= f.input :name %>
            <%= f.input :hourly_rate, placeholder:'£' %>
            <%= f.submit "update" %>
          <% end %>
      </div>
    <button type="button" class="btn btn-dark text-decoration-none"><%= link_to "Delete",
    organisation_path(@organisation),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></button>
  </div>
</div>

<div class="m-3">
  <h2>Shifts</h2>
  <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">Employee Name</th>
        <th scope="col">Shift Date</th>
        <th scope="col">Start Time</th>
        <th scope="col">Finish Time</th>
        <th scope="col">Break Length(minites)</th>
        <th scope="col">Overnight</th>
        <th scope="col">Sunday Shift</th>
        <th scope="col">Hours Worked</th>
        <th scope="col">Shift Pay</th>
      </tr>
    </thead>
    <tbody>
      <% @shifts.reverse.each do |shift| %>

      <tr>
        <th scope="row"><%=shift.organisation_user.user.name%></th>

        <td><%=shift.shift_date %></td>
        <td><%= shift.start_time %></td>
        <td><%= shift.finish_time%></td>
        <td><%= shift.break_length %></td>
        <td><%= shift.overnight ? "☑️" : " "%></td>
        <td><%= shift.sunday_shift ? "☑️" : " "%></td>
        <td><%= shift.hours_worked %></td>
        <td>£ <%= shift.final_pay %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>



<div class="shift-form">
      <%= simple_form_for [@organisation, @me, @shift] do |f| %>
      <div class="form-inputs">
        <%= f.input :shift_date, as: :date, require: true %>
        <%= f.input :start_time, as: :time, ignore_date: true, require: true %>
        <%= f.input :finish_time, as: :time, ignore_date: true, require: true %>
        <%= f.input :break_length, input_html: {min:"0", step:"10"} %>
        <%= f.submit "Create shift", class: "btn btn-secondary mt-3" %>
      </div>
      <% end %>
</div>
<% end %>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="row">

    <div class="col-6">

      <div class="left-cover">
        <h1>Welcome to Adnat</h1>
        <h2>Your smart shifts manager</h2>
        <div class="mt-5">
          <button type="button" class="btn btn-dark btn-lg"> <%= link_to "Log In", new_user_session_path %> </button>
          <button type="button" class="btn btn-outline-dark btn-lg"><%= link_to "Sign Up", new_user_registration_path %></button>
        </div>
      </div>
    </div>

    <div class="col-6" >
      <div class="right-cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1507914464562-6ff4ac29692f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80)">
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
 <div class="navbar">

    <% if user_signed_in? %>
    <h1> <%= link_to "Adnat", organisations_path %> </h1>
    <div class="d-flex">
      <p>Hello <%=current_user.name %>! </p>
      <%= link_to " Edit profile", edit_user_registration_path, class: "mx-2"%>
      <%= link_to " Log out ", destroy_user_session_path, data: {turbo_method: :delete} %>
    </div>

   <% else %>
    <h1><%= link_to "Adnat", root_path %> </h1>
    <p></p>
   <% end %>
</div>